Layout/TrailingWhitespace:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/UselessAssignment:
  Exclude:
    - "test/*.rb"

Layout/TrailingEmptyLines:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 110
  Exclude:
    - "test/*.rb"

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7
