name: blockchyp-ruby
on:
  push:
    branches:
      - "develop"
      - "master"
      - "preview"
    tags:
      - "*"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6-buster
    steps:
      - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: starting
          channel: '#gitactivity'
        if: always()
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - name: Run Build
        run: make build
      - name: Run Test
        run: make test
      - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: ${{ job.status }}
          channel: '#gitactivity'
        if: always()
  publish:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6-buster
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') && startsWith(github.ref_name, 'v') }}
    needs: [ test ]
    steps:
      - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: starting
          channel: '#gitactivity'
        if: always()
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - name: Run Build
        run: make build
      - name: Stage API Key
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials && chmod 0600 ~/.gem/credentials
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >> ~/.gem/credentials
      - name: Publish Rubygem
        run: make publish
      - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: ${{ job.status }}
          channel: '#gitactivity'
        if: always()